### PR TITLE
Add loginside tracker service

### PR DESCRIPTION
**Pull request by seia-soto**
I don't know the source company or organization of this tracker but found following image request from `https://www.jdsports.co.kr/`:

```
https://kakaostyle.loginside.co.kr/?uid=UNIQUE_USER_ID&tp=site&sv=20121203&st=1641428590061248495|1641429360038376563|1641428590061248495|0&vt=1641428590061248495|6|1641305984063241708|1|1641305984765E0M3M3&vk=0&ce=1&ri=0&re=1&dm=1920*1080&url=www.jdsports.co.kr%2F&ref=bookmark&ad_key=&ui=1&ag=&gd=&skey=&pd=&ct=&amt=&mr=&cd=24&tz=20&lg=ko-kr&trkses=1641428590061248495&trackurl=&RID=0.9872330801311584&
```

Also the url returns meaningless data: `[0]`

For host blocking, I added `kakaostyle.loginside.co.kr` too.

### CODE REVIEW

**Comment by piquark6046** [comment]
Youslist blocks only advertisement on a website.
If you use AdGuard, please close this, and reopen at https://github.com/adguardteam/adguardfilters.

**Comment by yous** [comment]
You can also add `kakaostyle.loginside.co.kr`, `loginside.co.kr` to `hosts.txt`.
```
0.0.0.0 kakaostyle.loginside.co.kr
```
```
0.0.0.0 loginside.co.kr
```

**Comment by seia-soto** [comment]
> Youslist blocks only advertisement on a website. If you want to block them, please close this, and reopen at [AdGuard](https://github.com/AdguardTeam/AdguardFilters) or [uBlockOrigin](https://github.com/uBlockOrigin/uAssets).

Thank you! However, in this case I think it's better to put rules to YousList as the rule is based on Korean website. I'll reflect your opinion and think once again in next time for better categorization.

**Comment by seia-soto** [comment]
> You can also add `kakaostyle.loginside.co.kr`, `loginside.co.kr` to `hosts.txt`.
> 
> ```
> 0.0.0.0 kakaostyle.loginside.co.kr
> ```
> 
> ```
> 0.0.0.0 loginside.co.kr
> ```

I've updated files:

- Remove `kakaostyle.loginside.co.kr` which is also blocked by `loginside.co.kr` in the rule.
- Add `kakaostyle.loginside.co.kr` and `loginside.co.kr` to hosts.txt.

**Comment by yous** [comment]
Thanks!

**Pull request merged**
