### PR TITLE
Block Naver top banner

### PR DESCRIPTION
**Pull request by x86chi**
88007635-5f4aa500-cb49-11ea-9397-ae6624770d6d

First-party ad at the top are not blocked

### CODE REVIEW

**Comment by yous** [comment]
Thanks for the PR. I think the domain should be `naver.com`, so can you please change the entry to `naver.com##div#NM_TOP_BANNER`?

**Comment by x86chi** [comment]
> Thanks for the PR. I think the domain should be `naver.com`, so can you please change the entry to `naver.com##div#NM_TOP_BANNER`?

No, It redirect to "www.naver.com"

ref: https://naver.com

**Comment by yous** [comment]
Aha, but it's okay to use `naver.com` as each filter will be applied to all subdomains. It's useful when the same elements exist on multiple subdomains, for example, `example.com`, `www.example.com`, and `m.example.com`. Also there are entries for `naver.com` already, so please add new entries between them.

**Comment by x86chi** [comment]
ok. I've apply your suggestion.

**Comment by yous** [comment]
@x86chi Thank you!

**Pull request merged**
