### PR TITLE
tracker: ab180

### PR DESCRIPTION
**Pull request by seia-soto**
### Review required

A mitigation for Airbridge product; specially in deep-linking web to app integration and data collection.

Live sample:
- `https://www.sirloin.co.kr/`

URL schemas:
```
core.airbridge.io/api/$version/apps/$appDirectory/$eventId
sdk.airbridge.io/data/$version/$appDirectory
```

- `$version` is the integration version between the data api and SDK
- `$appDirectory` is namespace identifier of AirBridge customer consisted of commonly used characters in HTTP URL; commonly viewed as application name (e.g. `my-application`)

I suggest adding `$xhr` and `$3p` if possible. However, I'm not sure about the status of sugar syntax support in YousList since the use of sugar syntax is literally low. In current version, I removed all sugars.

## Checks

1. General reproducability
2. Syntax consideration

### CODE REVIEW

**Comment by piquark6046** [comment]
Did you mean https://github.com/AdguardTeam/AdguardFilters/pull/129318?

**Comment by yous** [comment]
It seems they're using `https://static.airbridge.io/sdk/latest/airbridge.min.js`, is it okay to block it? If I block it then `core.airbirdge.io` and `sdk.airbridge.io` requests are gone.

**Comment by seia-soto** [comment]
> Did you mean [AdguardTeam/AdguardFilters#129318](https://github.com/AdguardTeam/AdguardFilters/pull/129318)?

Your previous contribution to adguard filters actually does the same thing compared to this.

**Comment by seia-soto** [comment]
> It seems they're using `https://static.airbridge.io/sdk/latest/airbridge.min.js`, is it okay to block it? If I block it then `core.airbirdge.io` and `sdk.airbridge.io` requests are gone.

Your suggestion resolves my concern on possible site breakages by blocking at domain level. Additionally, I confirmed the resource is not used on internal dashboard via business account including personal one.

**Comment by yous** [comment]
I rebased your branch with `||static.airbridge.io/sdk/latest/airbridge.min.js^`. Please have a check then I'll merge this.

**Comment by seia-soto** [comment]
I confirmed your changes.

**Comment by yous** [comment]
Thanks!

**Comment by piquark6046** [comment]
https://github.com/yous/YousList/pull/272#issuecomment-1666083068

Why? The topic of the contribution to AdguardFilters and this PR is same.
Did you mean that there is a difference at blocking level?

**Comment by seia-soto** [comment]
> [#272 (comment)](https://github.com/yous/YousList/pull/272#issuecomment-1666083068)
> 
> Why? The topic of the contribution to AdguardFilters and this PR is same. Did you mean that there is a difference at blocking level?

I don't understand what's your purpose to say like that.

**Pull request merged**
