### PR TITLE
incorrect-blocking: instiz.net

### PR DESCRIPTION
**Pull request by seia-soto**
URL: https://www.instiz.net/name_enter?category=42

<details>
<summary>Screenshot</summary>

image

</details>

### CODE REVIEW

**Comment by yous** [comment]
I think we have to hide the first `.board_img_foot`, not the second one. How about this?

```
instiz.net##div.board_img_foot:not([style])
```

**Comment by seia-soto** [comment]
Sorry, I was late due to lack of time. I agree with you.

**Review by seia-soto — COMMENTED** [review]
self.

```suggestion
instiz.net##div.board_img_foot:not([style])
```

**Comment by yous** [comment]
Thanks!

**Pull request merged**
