### PR TITLE
Fixes #201 (Update 20220312) - Update for namu.wiki banner

### LINKED ISSUE #201: 나무위키 하단 파워링크
나무위키 개별 항목 하단 파워링크 광고가 언제인가부터 차단이 안되고 있습니다. 차단 지원 해주시면 좋을 것 같습니다.

예제: https://namu.wiki/w/uBlock%20Origin

### PR DESCRIPTION
**Pull request by seia-soto**
This PR simply removes namu.wiki content ad banner at bottom. Even compatible with previous version of banner.

image

image

### CODE REVIEW

**Comment by yous** [comment]
Thanks for the idea! I've edited your rule for some accuracy, how about this?

```
namu.wiki##article>p+div div[id]:has(div[id]:has(div[id]>ul>li,div>a[href*="/w/%EB%B6%84%EB%A5%98:"]))~div:has(img[src*="//w.namu.la/s/"])
```

Also, this is using `:has()` extension, so can you please move the rule under "Extended selectors" section? I think we can remove previous two rules:

```
namu.wiki##:xpath(//article//div[count(div[*[*[*]]])=2][count(div[*[*[*]]][1]//img[starts-with(@src,'//w.namu.la/s/')])>2][div[*[*[*]]][2][count(div[@class]/div[last()][count(div[count(div)>0 and count(div)<=2])=3])>=2]])
namu.wiki##:xpath(//article//div[count(div[*[*[*]]])=2][count(div[*[*[*]]][1]//img[starts-with(@src,'data:image/png;base64,')])>2][div[*[*[*]]][2][count(div[@class]/div[last()][count(div[count(div)>0 and count(div)<=2)=3])>=2]])
```

**Comment by seia-soto** [comment]
I applied your suggestions! Looks nice.

Why I didn't write full address of the image host was to reduce the sensitivity of the rule. However, I think still it's better to leave things more intuitive.

**Comment by seia-soto** [comment]
Do we need to handle the case of image source url starting with `data:image/png;base64`? I didn't find it on the site but still works well.

**Comment by seia-soto** [comment]
Also, I didn't change the version, yet. Please, consider updating version if required.

**Comment by seia-soto** [comment]
Yous, please consider contributing this rule to List-KR for more people to get the advantage. I think you need to do or I need to get your agree as your improvement included.

Please, also refer:

- https://github.com/List-KR/List-KR/issues/202#issuecomment-1065928994

**Comment by yous** [comment]
@seia-soto, feel free to contribute this rule to other filters. I'll add `data:image/png;base64,` too:
```
namu.wiki##article>p+div div[id]:has(div[id]:has(div[id]>ul>li,div>a[href*="/w/%EB%B6%84%EB%A5%98:"]))~div:has(img[src*="//w.namu.la/s/"],img[src^="data:image/png;base64,"])
```

**Comment by yous** [comment]
Thanks! Updated version and image source in 0f868e1.

**Comment by seia-soto** [comment]
Thanks! All confirmed.

**Pull request merged**
