### PR TITLE
Fixes #196 — coupang ad on clien.net

### LINKED ISSUE #196: clien.net
https://www.clien.net/service/search?q=yous
https://m.clien.net/service/search?q=yous
coupang ad

### PR DESCRIPTION
**Pull request by seia-soto**
This PR fixes coupang advertisement on `clien.net` and `m.clien.net`.

I didn't change the version as there was a recent release.

Related issues:
- #196

### CODE REVIEW

**Review by piquark6046 — CHANGES_REQUESTED** [review]
Maybe the following rule can block advertisement request of clien.net
``` 
||clien.net/service/api/coupang/ad?
```
https://github.com/List-KR/List-KR/commit/6d9187a7ae4b7d1a5c81b56a38f65b93200bb617

**Comment by yous** [comment]
Thanks for letting me know, @piquark6046.

```
||clien.net/service/api/coupang/ad^
||clien.net/service/js/common/clien.naver.js^
```

Also,

```
clien.net##div#coupangAd
m.clien.net##div#coupangAd
m.clien.net##div.search_list_ad
```
instead of `##div.coupang-ad`, `##div.coupang_ad`.

**Comment by seia-soto** [comment]
Thank you all! Do you think it is better to add same rules to the youslist? I'll wait for the conclusion of this PR.

Still, we have to think some points:
- uBO doesn't include List-KR by default as I know and seems like this is why I didn't notice.
- Most of Koreans use both filters. All clients will shrink duplicate rules but this may add useless work.

I want to hear your voices.

**Comment by yous** [comment]
List-KR has started from YousList: <https://list-kr.github.io/#credits>. But List-KR diverged as they use experimental syntaxes like executing scripts. YousList is sticking to Adblock Plus syntaxes, because it's compatible with 1Blocker.

I don't use other filters, and I don't want YousList depend on other filters (but there are [exceptions](https://github.com/yous/YousList/blob/b4d638546f323feb815bf9a26d230f4da5fbe9b5/youslist.txt#L7424-L7434)).

**Comment by seia-soto** [comment]
Thanks for your description. I'll apply your improvements for better approach soon!

**Comment by piquark6046** [comment]
https://github.com/yous/YousList/pull/197#issuecomment-1010250364

Please note that new version of List-KR called as lightway will be not depend YousList.

**Comment by seia-soto** [comment]
I've applied your improvements. May I request check if it is ok to merge `clien.net##div#coupangAd` with `m.clien.net##div#coupangAd`?

`clien.net##div#coupangAd` also works on `m.clien.net` as I know.

**Comment by yous** [comment]
Okay, merging.

**Pull request merged**
